// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    Card: typeof import('./components/Card.vue')['default']
    Catalog: typeof import('./components/Catalog.vue')['default']
    CategoryPreview: typeof import('./components/CategoryPreview.vue')['default']
    CorrespondingTissueCard: typeof import('./components/CorrespondingTissueCard.vue')['default']
    ElevatedCard: typeof import('./components/ElevatedCard.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    Headline: typeof import('./components/Headline.vue')['default']
    HeadlineWithText: typeof import('./components/HeadlineWithText.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Magnification: typeof import('./components/Magnification.vue')['default']
    MoreProducts: typeof import('./components/MoreProducts.vue')['default']
    Nav: typeof import('./components/Nav.vue')['default']
    ProductMagnifier: typeof import('./components/ProductMagnifier.vue')['default']
    Search: typeof import('./components/Search.vue')['default']
    Section: typeof import('./components/Section.vue')['default']
    SplitImage: typeof import('./components/SplitImage.vue')['default']
    TwoColumn: typeof import('./components/TwoColumn.vue')['default']
  }
}

export { }
